-- DDL statement for to create the DisGeneTable
CREATE TABLE for DisGeneTable (
    variantID VARCHAR(25),
    gene_symbol VARCHAR(25),
    variant_consquence VARCHAR(25),
    disease_name VARCHAR(125),
    score INT,
    PRIMARY KEY (variantID, gene_symbol)
);
-- DDL statement for to create the DisGeneTable
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs145588689","ADAR","missense variant","AICARDI-GOUTIERES SYNDROME 6",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs28936681","ADAR","missense variant","Symmetrical dyschromatosis of extremities",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs28936681","CHRNB2","missense variant","Symmetrical dyschromatosis of extremities",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs398122892","ADAR","missense variant","AICARDI-GOUTIERES SYNDROME 6",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs398122894","ADAR","missense variant","AICARDI-GOUTIERES SYNDROME 6",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs398122896","ADAR","missense variant","AICARDI-GOUTIERES SYNDROME 6",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs1044845711","ADAR","missense variant","Symmetrical dyschromatosis of extremities",0.72);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs1044845711","CHRNB2","missense variant","Symmetrical dyschromatosis of extremities",0.72);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs1288116010","EPRS1","missense variant","LEUKODYSTROPHY, HYPOMYELINATING, 15",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs898824971","EPRS1","missense variant","LEUKODYSTROPHY, HYPOMYELINATING, 15",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs876657403","PYCR2","missense variant","LEUKODYSTROPHY, HYPOMYELINATING, 10",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs267606847","GJC2","missense variant","LYMPHATIC MALFORMATION 3",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs74315312","GJC2","missense variant","Leukodystrophy, Hypomyelinating, 2",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs75469429","GJC2","missense variant","SPASTIC PARAPLEGIA 44, AUTOSOMAL RECESSIVE (disorder)",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs397514598","PNPT1","missense variant","COMBINED OXIDATIVE PHOSPHORYLATION DEFICIENCY 13",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs148674363","TET3","missense variant","MULTIPLE MITOCHONDRIAL DYSFUNCTIONS SYNDROME 2 WITH HYPERGLYCINEMIA",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs148674363","BOLA3","missense variant","MULTIPLE MITOCHONDRIAL DYSFUNCTIONS SYNDROME 2 WITH HYPERGLYCINEMIA",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs66468541","HSPD1","missense variant","Spastic paraplegia 13, autosomal dominant",0.81);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199422224","NDUFS1","missense variant","MITOCHONDRIAL COMPLEX I DEFICIENCY, NUCLEAR TYPE 5",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs189360006","DAG1","missense variant","MUSCULAR DYSTROPHY-DYSTROGLYCANOPATHY (LIMB-GIRDLE), TYPE C, 9",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs797045023","DAG1","missense variant","MUSCULAR DYSTROPHY-DYSTROGLYCANOPATHY (CONGENITAL WITH BRAIN AND EYE ANOMALIES), TYPE A, 9",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs144133667","LIAS","missense variant","HYPERGLYCINEMIA, LACTIC ACIDOSIS, AND SEIZURES",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs369398935","RARS1","missense variant","LEUKODYSTROPHY, HYPOMYELINATING, 9",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs371802902","POLR1C","missense variant","LEUKODYSTROPHY, HYPOMYELINATING, 11",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs796052127","POLR1C","missense variant","LEUKODYSTROPHY, HYPOMYELINATING, 11",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs201320592","POLR1C","missense variant","LEUKODYSTROPHY, HYPOMYELINATING, 11",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs1350566881","FBXL4","missense variant","FBXL4-related encephalomyopathic mitochondrial DNA depletion syndrome",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs201989042","FBXL4","missense variant","FBXL4-related encephalomyopathic mitochondrial DNA depletion syndrome",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs772037717","FBXL4","missense variant","FBXL4-related encephalomyopathic mitochondrial DNA depletion syndrome",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs72549407","FAM126A","missense variant","HYPOMYELINATION AND CONGENITAL CATARACT",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs121434455","PEX1","missense variant","Infantile Refsum Disease (disorder)",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs370483961","PEX1","missense variant","HEIMLER SYNDROME 1",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs61750427","PEX1","missense variant","Infantile Refsum Disease (disorder)",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs61750427","GATAD1","missense variant","Infantile Refsum Disease (disorder)",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs61750407","PEX1","missense variant","PEROXISOME BIOGENESIS DISORDER 1A (ZELLWEGER)",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs61750429","PEX1","missense variant","Infantile Refsum Disease (disorder)",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs61750429","GATAD1","missense variant","Infantile Refsum Disease (disorder)",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs776679653","ISCA1","missense variant","MULTIPLE MITOCHONDRIAL DYSFUNCTIONS SYNDROME 5",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs202080674","ERCC6","missense variant","Cockayne Syndrome, Type II",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs751292948","ERCC6","stop gained","Cockayne Syndrome, Type II",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs1365187961","ERCC6","missense variant","Colorectal Carcinoma",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs121918103","PSAP","missense variant","Metachromatic Leukodystrophy due to Saposin B Deficiency",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs121918107","PSAP","missense variant","Metachromatic Leukodystrophy due to Saposin B Deficiency",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs770171865","PSAP","missense variant","Metachromatic Leukodystrophy due to Saposin B Deficiency",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs1399429058","POLR3A","missense variant","Wiedemann-Rautenstrauch syndrome",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs757209071","POLR3A","missense variant","Wiedemann-Rautenstrauch syndrome",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs778985686","POLR3A","missense variant","Wiedemann-Rautenstrauch syndrome",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs1307896663","POLR3A","missense variant","Leukodystrophy, Hypomyelinating, with Hypodontia and Hypogonadotropic Hypogonadism",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs371703979","POLR3A","missense variant","Leukodystrophy, Hypomyelinating, with Hypodontia and Hypogonadotropic Hypogonadism",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs397514472","PEX16","missense variant","PEROXISOME BIOGENESIS DISORDER 8B",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs1554988032","ACER3","missense variant","LEUKODYSTROPHY, PROGRESSIVE, EARLY CHILDHOOD-ONSET",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs1442212683","POLR3B","missense variant","LEUKODYSTROPHY, HYPOMYELINATING, 8, WITH OR WITHOUT OLIGODONTIA AND/OR HYPOGONADOTROPIC HYPOGONADISM",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs397515440","NUBPL","missense variant","MITOCHONDRIAL COMPLEX I DEFICIENCY, NUCLEAR TYPE 21",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs765487627","GLRX5","missense variant","ANEMIA, SIDEROBLASTIC, 3, PYRIDOXINE-REFRACTORY",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs121434578","ABAT","missense variant","Gamma aminobutyric acid transaminase deficiency",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs121918217","FA2H","missense variant","Leukodystrophy, Dysmyelinating, And Spastic Paraparesis With Or Without Dystonia",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199473673","CTC1","missense variant","CEREBRORETINAL MICROANGIOPATHY WITH CALCIFICATIONS AND CYSTS 1",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199473678","CTC1","missense variant","CEREBRORETINAL MICROANGIOPATHY WITH CALCIFICATIONS AND CYSTS 1",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs369255297","CTC1","missense variant","CEREBRORETINAL MICROANGIOPATHY WITH CALCIFICATIONS AND CYSTS 1",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs387907080","CTC1","missense variant","CEREBRORETINAL MICROANGIOPATHY WITH CALCIFICATIONS AND CYSTS 1",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199473681","CTC1","missense variant","CEREBRORETINAL MICROANGIOPATHY WITH CALCIFICATIONS AND CYSTS 1",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs779027563","CNTNAP1","missense variant","NEUROPATHY, CONGENITAL HYPOMYELINATING, 3",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs118204090","ACOX1","missense variant","Peroxisomal ACYL-COA oxidase deficiency",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs118204092","ACOX1","missense variant","Peroxisomal ACYL-COA oxidase deficiency",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs780887410","ACOX1","missense variant","Peroxisomal ACYL-COA oxidase deficiency",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs483352809","TUBB4A","missense variant","Leukodystrophy, Hypomyelinating, 6",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs76436818","RNASEH2A","missense variant","AICARDI-GOUTIERES SYNDROME 4",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs76436818","HOOK2","missense variant","AICARDI-GOUTIERES SYNDROME 4",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs77103971","RNASEH2A","missense variant","AICARDI-GOUTIERES SYNDROME 4",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs77103971","HOOK2","missense variant","AICARDI-GOUTIERES SYNDROME 4",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs121909602","COX6B1","missense variant","Cytochrome-c Oxidase Deficiency",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs121912420","SERPIND1","missense variant","Heparin cofactor II deficiency (disorder)",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs121912420","PI4KA","missense variant","Heparin cofactor II deficiency (disorder)",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs747119727","PI4KA","missense variant","POLYMICROGYRIA, PERISYLVIAN, WITH CEREBELLAR HYPOPLASIA AND ARTHROGRYPOSIS",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs121909117","POLR2F","missense variant","Waardenburg Syndrome, Type 4c",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs121909117","SOX10","missense variant","Waardenburg Syndrome, Type 4c",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs74315515","POLR2F","missense variant","WAARDENBURG SYNDROME, TYPE IIE",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs74315515","SOX10","missense variant","WAARDENBURG SYNDROME, TYPE IIE",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs148092995","ARSA","missense variant","Leukodystrophy, Metachromatic",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199476366","ARSA","missense variant","Leukodystrophy, Metachromatic",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs74315459","ARSA","missense variant","Leukodystrophy, Metachromatic",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs74315480","ARSA","missense variant","Leukodystrophy, Metachromatic",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199476357","ARSA","missense variant","Leukodystrophy, Metachromatic",0.71);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199476374","ARSA","missense variant","Leukodystrophy, Metachromatic",0.71);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199476385","ARSA","missense variant","Leukodystrophy, Metachromatic",0.71);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs28940895","ARSA","missense variant","Leukodystrophy, Metachromatic",0.71);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs6151425","ARSA","missense variant","Leukodystrophy, Metachromatic",0.71);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs148403406","ARSA","missense variant","Leukodystrophy, Metachromatic",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199476340","ARSA","missense variant","Leukodystrophy, Metachromatic",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199476342","ARSA","missense variant","Leukodystrophy, Metachromatic",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199476344","ARSA","missense variant","Leukodystrophy, Metachromatic",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199476347","ARSA","missense variant","Leukodystrophy, Metachromatic",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199476350","ARSA","missense variant","Leukodystrophy, Metachromatic",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199476353","ARSA","missense variant","Leukodystrophy, Metachromatic",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199476360","ARSA","stop gained","Leukodystrophy, Metachromatic",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199476364","ARSA","missense variant","Leukodystrophy, Metachromatic",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199476367","ARSA","missense variant","Leukodystrophy, Metachromatic",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199476370","ARSA","missense variant","Leukodystrophy, Metachromatic",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199476372","ARSA","missense variant","Leukodystrophy, Metachromatic",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199476376","ARSA","missense variant","Leukodystrophy, Metachromatic",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199476378","ARSA","missense variant","Leukodystrophy, Metachromatic",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199476381","ARSA","missense variant","Leukodystrophy, Metachromatic",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199476389","ARSA","missense variant","Leukodystrophy, Metachromatic",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs199476392","ARSA","missense variant","Leukodystrophy, Metachromatic",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs74315462","ARSA","missense variant","Leukodystrophy, Metachromatic",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs74315484","ARSA","missense variant","Leukodystrophy, Metachromatic",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs104894931","SLC16A2","missense variant","Allan-Herndon-Dudley syndrome (AHDS)",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs104894938","SLC16A2","missense variant","Allan-Herndon-Dudley syndrome (AHDS)",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs122455132","SLC16A2","missense variant","Allan-Herndon-Dudley syndrome (AHDS)",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs373279555","SLC16A2","missense variant","Allan-Herndon-Dudley syndrome (AHDS)",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs727504155","SLC16A2","missense variant","Allan-Herndon-Dudley syndrome (AHDS)",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs281864468","AIFM1","missense variant","COWCHOCK SYNDROME",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs281864468","RAB33A","missense variant","COWCHOCK SYNDROME",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs724160021","AIFM1","missense variant","DEAFNESS, X-LINKED 5 (disorder)",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs724160021","RAB33A","missense variant","DEAFNESS, X-LINKED 5 (disorder)",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs724160023","AIFM1","missense variant","DEAFNESS, X-LINKED 5 (disorder)",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs724160023","RAB33A","missense variant","DEAFNESS, X-LINKED 5 (disorder)",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs863225431","AIFM1","missense variant","DEAFNESS, X-LINKED 5 (disorder)",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs863225431","RAB33A","missense variant","DEAFNESS, X-LINKED 5 (disorder)",0.8);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs1223488720","AIFM1","missense variant","DEAFNESS, X-LINKED 5 (disorder)",0.7);
INSERT INTO DisGeneTable (variantID,gene_symbol,variant_consquence,disease_name,score) VALUES ("rs1223488720","RAB33A","missense variant","DEAFNESS, X-LINKED 5 (disorder)",0.7);
