-- Name: Emma Carlson
-- EMAIL: eecarlson@unomaha.edu
-- Class: BIOI 4870/CSCI 8876, Spring 2022 
-- Assignment 2
-- 
-- Honor Pledge: On my honor as a student of the University of Nebraska at 
-- Omaha, I have neither given nor received unauthorized help on 
-- this programming assignment.
-- 
-- Partners: NONE
-- 

-- DDL Statement to create table with leukodystrophies from OMIM; data downloaded directly from:
-- https://www.omim.org/search?index=clinicalSynopsis&start=1&search=leukodystrophy

-- Data parsed and reformated with OMIM_Results_Parse.py

-- DDL statement for to create the LeukoDiseasesOMIM
CREATE TABLE LeukoDiseasesOMIM( 
    OMIM_Num INT, 
    disease_name VARCHAR(125),
    entrez_geneID VARCHAR(10),
    PRIMARY KEY (OMIM_Num)
);

-- DML insert statements for LeukoDiseasesOMIM table
-- Generated with https://www.convertcsv.com/csv-to-sql.htm from LeukoDiseasesOMIMProcessed.csv
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (169500, 'LEUKODYSTROPHY, DEMYELINATING, ADULT-ONSET, AUTOSOMAL DOMINANT','ADLD');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (249900,'METACHROMATIC LEUKODYSTROPHY DUE TO SAPOSIN B DEFICIENCY','MLDSAPB');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (250100,'METACHROMATIC LEUKODYSTROPHY','MLD');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (260600,'LEUKODYSTROPHY, HYPOMYELINATING, 3','HLD3');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (616140,'LEUKODYSTROPHY, HYPOMYELINATING, 9','HLD9');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (616420,'LEUKODYSTROPHY, HYPOMYELINATING, 10','HLD10');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (616494,'LEUKODYSTROPHY, HYPOMYELINATING, 11','HLD11');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (616531,'NEURODEVELOPMENTAL DISORDER WITH SPASTICITY, HYPOMYELINATING LEUKODYSTROPHY, AND BRAIN ABNORMALITIES','NEDSPLB');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (616683,'LEUKODYSTROPHY, HYPOMYELINATING, 12','HLD12');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (616763,'LEUKODYSTROPHY AND ACQUIRED MICROCEPHALY WITH OR WITHOUT DYSTONIA','LDAMD');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (616881,'LEUKODYSTROPHY, HYPOMYELINATING, 13','HLD13');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (617560,'SPASTIC ATAXIA 8, AUTOSOMAL RECESSIVE, WITH HYPOMYELINATING LEUKODYSTROPHY','SPAX8');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (617762,'LEUKODYSTROPHY, PROGRESSIVE, EARLY CHILDHOOD-ONSET','PLDECO');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (614381,'LEUKODYSTROPHY, HYPOMYELINATING, 8, WITH OR WITHOUT OLIGODONTIA AND/OR HYPOGONADOTROPIC HYPOGONADISM','HLD8');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (300232,'SPONDYLOEPIMETAPHYSEAL DYSPLASIA, X-LINKED, WITH HYPOMYELINATING LEUKODYSTROPHY','SEMDHL');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (612233,'LEUKODYSTROPHY, HYPOMYELINATING, 4','HLD4');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (612438,'LEUKODYSTROPHY, HYPOMYELINATING, 6','HLD6');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (608804,'LEUKODYSTROPHY, HYPOMYELINATING, 2','HLD2');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (610532,'LEUKODYSTROPHY, HYPOMYELINATING, 5','HLD5');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (607694,'LEUKODYSTROPHY, HYPOMYELINATING, 7, WITH OR WITHOUT OLIGODONTIA AND/OR HYPOGONADOTROPIC HYPOGONADISM','HLD7');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (617899,'LEUKODYSTROPHY, HYPOMYELINATING, 14','HLD14');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (617951,'LEUKODYSTROPHY, HYPOMYELINATING, 15','HLD15');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (617964,'LEUKODYSTROPHY, HYPOMYELINATING, 16','HLD16');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (618006,'LEUKODYSTROPHY, HYPOMYELINATING, 17','HLD17');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (618404,'LEUKODYSTROPHY, HYPOMYELINATING, 18','HLD18');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (618688,'LEUKODYSTROPHY, HYPOMYELINATING, 19, TRANSIENT INFANTILE','HLD19');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (618863,'RETINAL DYSTROPHY WITH LEUKODYSTROPHY','RDLKD');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (619071,'LEUKODYSTROPHY, HYPOMYELINATING, 20','HLD20');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (619310,'LEUKODYSTROPHY, HYPOMYELINATING, 21','HLD21');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (619328,'LEUKODYSTROPHY, HYPOMYELINATING, 22','HLD22');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (619688,'LEUKODYSTROPHY, HYPOMYELINATING, 23, WITH ATAXIA, DEAFNESS, LIVER DYSFUNCTION, AND DILATED CARDIOMYOPATHY','HLD23');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (156310,'METACHROMATIC LEUKODYSTROPHY, ADULT-ONSET, WITH NORMAL ARYLSULFATASE A',NULL);
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (615330,'MULTIPLE MITOCHONDRIAL DYSFUNCTIONS SYNDROME 3','MMDS3');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (601539,'PEROXISOME BIOGENESIS DISORDER 1B','PBD1B');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (252010,'MITOCHONDRIAL COMPLEX I DEFICIENCY, NUCLEAR TYPE 1','MC1DN1');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (264470,'PEROXISOMAL ACYL-CoA OXIDASE DEFICIENCY',NULL);
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (266150,'PYRUVATE CARBOXYLASE DEFICIENCY',NULL);
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (616034,'2,4-DIENOYL-CoA REDUCTASE DEFICIENCY','DECRD');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (616370,'MULTIPLE MITOCHONDRIAL DYSFUNCTIONS SYNDROME 4','MMDS4');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (616538,'MUSCULAR DYSTROPHY-DYSTROGLYCANOPATHY (CONGENITAL WITH BRAIN AND EYE ANOMALIES), TYPE A, 9','MDDGA9');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (616859,'SPASTICITY, CHILDHOOD-ONSET, WITH HYPERGLYCINEMIA','SPAHGC');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (617613,'MULTIPLE MITOCHONDRIAL DYSFUNCTIONS SYNDROME 5','MMDS5');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (614299,'MULTIPLE MITOCHONDRIAL DYSFUNCTIONS SYNDROME 2 WITH HYPERGLYCINEMIA','MMDS2');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (614462,'HYPERGLYCINEMIA, LACTIC ACIDOSIS, AND SEIZURES','HGCLAS');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (614561,'LEUKOENCEPHALOPATHY, BRAIN CALCIFICATIONS, AND CYSTS','LCC');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (614877,'PEROXISOME BIOGENESIS DISORDER 8B','PBD8B');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (614932,'COMBINED OXIDATIVE PHOSPHORYLATION DEFICIENCY 13','COXPD13');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (615010,'AICARDI-GOUTIERES SYNDROME 6','AGS6');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (615471,'MITOCHONDRIAL DNA DEPLETION SYNDROME 13 (ENCEPHALOMYOPATHIC TYPE)','MTDPS13');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (278800,'DE SANCTIS-CACCHIONE SYNDROME',NULL);
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (300523,'ALLAN-HERNDON-DUDLEY SYNDROME','AHDS');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (612199,'CEREBRORETINAL MICROANGIOPATHY WITH CALCIFICATIONS AND CYSTS 1','CRMCC1');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (612319,'SPASTIC PARAPLEGIA 35, AUTOSOMAL RECESSIVE, WITH OR WITHOUT NEURODEGENERATION','SPG35');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (613163,'GABA-TRANSAMINASE DEFICIENCY',NULL);
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (609136,'PERIPHERAL DEMYELINATING NEUROPATHY, CENTRAL DYSMYELINATION, WAARDENBURG SYNDROME, AND HIRSCHSPRUNG DISEASE','PCWH');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (610333,'AICARDI-GOUTIERES SYNDROME 4','AGS4');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (610678,'COMBINED OXIDATIVE PHOSPHORYLATION DEFICIENCY 4','COXPD4');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (618186,'NEUROPATHY, CONGENITAL HYPOMYELINATING, 3','CHN3');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (618226,'MITOCHONDRIAL COMPLEX I DEFICIENCY, NUCLEAR TYPE 5','MC1DN5');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (618235,'MITOCHONDRIAL COMPLEX I DEFICIENCY, NUCLEAR TYPE 13','MC1DN13');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (618242,'MITOCHONDRIAL COMPLEX I DEFICIENCY, NUCLEAR TYPE 21','MC1DN21');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (619051,'MITOCHONDRIAL COMPLEX IV DEFICIENCY, NUCLEAR TYPE 7','MC4DN7');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (619061,'MITOCHONDRIAL COMPLEX IV DEFICIENCY, NUCLEAR TYPE 17','MC4DN17');
INSERT INTO LeukoDiseasesOMIM(OMIM_Num,disease_name,entrez_geneID) VALUES (221790,'DERMATOLEUKODYSTROPHY',NULL);
